### ISSUE TITLE
Latest push to master

### ISSUE THREAD

**Issue by bmwasaru** [tumtech/tumtech.github.io#4]
The icons are not visible. Please do test the icons on your local machine before you push. Anyway, I thought we agree that we don't need them.

The calendar seems to have package dependencies like grunt in the package.json file, so we cannot leverage the free githib.io hosting with those dependencies. 

:v:

**Comment by joelmwas** [comment]
Ooo I had not noted that. I thought it was just javascript.

**Comment by joelmwas** [comment]
I have removed them *

**Comment by GochoMugo** [comment]
@bmwasaru the dependencies in the package.json are all __development__ dependencies. The site will do just fine without the dependencies.

**Comment by bmwasaru** [comment]
@GochoMugo I agree, what we really need was simple gh-pages since we do not have a server to host the website.

**Comment by GochoMugo** [comment]
[Github pages](https://pages.github.com) will be enough for your requirements, I assume. It has some super-powers if I might say :cow:

**Comment by bmwasaru** [comment]
Yes it does. The gh-pages branches exists.
