### ISSUE TITLE
Irrelevant README

### ISSUE THREAD

**Issue by GochoMugo** [tumtech/tumtech.github.io#5]
The current [README](https://github.com/tumtech/tumtech.github.io/blob/master/README.md) seems very irrelevent to what to the contents of the repository. Mind looking :eyes: at that?

**Comment by bmwasaru** [comment]
Thank you @GochoMugo, @joelmwas made some changes I forgot to remove the unnecessary files plus editing the readme file

**Comment by GochoMugo** [comment]
Actually the [REAMDE.md](https://github.com/tumtech/tumtech.github.io/blob/master/README.md) is hiding the [readme.md](https://github.com/tumtech/tumtech.github.io/blob/master/readme.md). It has a higher precedence to Github. It is now fixed. :smiley:

**Comment by bmwasaru** [comment]
Great. I have also removed the unused calendar that @joelmwas wanted to remove
